name: flutter_application_farisaanr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/smk-ypc.png
    - images/WhatsApp Image 2025-08-12 at 11.09.18 AM.jpeg
    - images/vm1.jpg
    - images/vm2.jpg
    - images/vm3.jpg
    - images/pmd.jpeg
    - images/gn.jpg
    - images/pm.jpeg
    - images/pmd.jpeg
    - images/pt.jpg
